# Site settings
title: Welcome to 52Dreams!
description: A blog about lorem ipsum dolor sit amet
baseurl: "/52dream.github.io" # the subpath of your site, e.g. /blog
url: "https://spiritgs.github.io/52dream.github.io/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Andy Hunter
user_description: The time you got up early, the time you worked hard, the time you stayed up late, the time you spent studying hard, the time when you felt you were not working hard and feeling too tired, those you do not want to persecute yourself, but still choose to continue to do that time, that is to pursue the meaning of the dream.
user_title: Math_Teacher  Pythoner
email: spirit.nj@gmail.com
twitter_username: 52dreams_
github_username:  spiritgs
gplus_username:  

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
